version: '3.3'
services:
    project-app:
      build: ./
      image: spring-boot:1.0
      restart: always
      container_name: project-app
      ports:
        - 8080:8080
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
      network_mode: bridge
